### ISSUE TITLE
Deliverable #3 : High Level Design Final Draft 

### ISSUE THREAD

**Issue by abhiroopsingh** [abhiroopsingh/LoyaltySystem#5]
Here is the link to the final draft of the deliverable. Make any changes that you guys see fit.

Google Doc: https://docs.google.com/document/d/1Tj4LoMN2R_dJtBDAkM_cluQ8fmTLvF0vyqXTsgqLZW0/edit

**Comment by AndySin** [comment]
Needs Architecture Design as well

**Comment by akhilg96** [comment]
Both architecture design & system sequence diagrams were submitted individually.
