### ISSUE TITLE
Detailed Class Diagram. Let me know of any updates.

### ISSUE THREAD

**Issue by abhiroopsingh** [abhiroopsingh/LoyaltySystem#7]
![detailed class diagram](https://cloud.githubusercontent.com/assets/23176963/20080144/14cd1cb8-a516-11e6-81e7-70cddf45f94b.png)

**Comment by abhiroopsingh** [comment]
[Class Diagram Text.docx](https://github.com/abhiroopsingh/LoyaltySystem/files/576885/Class.Diagram.Text.docx)

**Comment by akhilg96** [comment]
Added multiplicities. Will post the final pdf document that I am going to submit soon.

**Comment by akhilg96** [comment]
This is one of the documents I will be submitting. Waiting for Andy's response about primary/foreign keys.
[Group1_Class_Diagram.pdf](https://github.com/abhiroopsingh/LoyaltySystem/files/578586/Group1_Class_Diagram.pdf)
