### ISSUE TITLE
Database Entity Relationship Diagram and Tables

### ISSUE THREAD

**Issue by AndySin** [abhiroopsingh/LoyaltySystem#8]
[Database Entity Relation.pdf](https://github.com/abhiroopsingh/LoyaltySystem/files/577294/Database.Entity.Relation.pdf)

**Comment by akhilg96** [comment]
Could you please format it neatly AND add a header for the 2 diagrams? Right now, the the pdf file looks all jumbled up... Thanks

**Comment by AndySin** [comment]
revised

**Comment by AndySin** [comment]
[Database Entity Relation.pdf](https://github.com/abhiroopsingh/LoyaltySystem/files/577321/Database.Entity.Relation.pdf)

**Comment by akhilg96** [comment]
Formatted your ER diagram. For the database tables, you also need to: "Describe which attribute(s) represent the primary key for each table and which attribute(s) are foreign keys to other tables." 
[Group1_ER_Diagram.pdf](https://github.com/abhiroopsingh/LoyaltySystem/files/578679/Group1_ER_Diagram.pdf)

**Comment by akhilg96** [comment]
Database tables. Submitted deliverable 4. 
[Group1_Database_Tables.pdf](https://github.com/abhiroopsingh/LoyaltySystem/files/581445/Group1_Database_Tables.pdf)
